# 基础镜像
FROM redis
# author
MAINTAINER VrmlStudio

# 挂载目录
VOLUME /home/VrmlStudio/redis
# 创建目录
RUN mkdir -p /home/VrmlStudio/redis
# 指定路径
WORKDIR /home/VrmlStudio/redis
# 复制conf文件到路径
COPY ./conf/redis.conf /home/VrmlStudio/redis/redis.conf
