# 基础镜像
FROM nginx
# author
MAINTAINER VrmlStudio

# 挂载目录
VOLUME /home/VrmlStudio/projects/VrmlStudio-ui
# 创建目录
RUN mkdir -p /home/VrmlStudio/projects/VrmlStudio-ui
# 指定路径
WORKDIR /home/VrmlStudio/projects/VrmlStudio-ui
# 复制conf文件到路径
COPY ./conf/nginx.conf /etc/nginx/nginx.conf
# 复制html文件到路径
COPY ./html/dist /home/VrmlStudio/projects/VrmlStudio-ui
